Project2_Auction/commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create/", views.create_listing, name="create_listing"),
    path("listing/<int:listing_id>/", views.listing, name="listing"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("categories/", views.categories, name="categories"),
    path("categories/<str:category_name>", views.category_listing, name="category_listing")
]

Project2_Auction/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

Project2_Auction/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Listing(models.Model):

    title = models.CharField(max_length=64)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    image_url = models.URLField(blank=True, null=True, max_length=500)
    category = models.CharField(max_length=64, blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listing")
    is_active = models.BooleanField(default=True)
    winner = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name="won_listing")
    watchlist = models.ManyToManyField(User, blank=True, related_name="watchlist")
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - Active: {self.is_active}"
    


class Bid(models.Model):

    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bid_user")
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.amount} by {self.bidder} on {self.listing.title}"
    



class Comment(models.Model):
    
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.author} on {self.listing.title}"

Project2_Auction/commerce/auctions/forms.py
from django import forms
from .models import Listing

CATEGORY_CHOICES = [
    ('', 'Select Category'),
    ('Fashion', 'Fashion'),
    ('Toys', 'Toys'),
    ('Electronics', 'Electronics'),
    ('Home', 'Home'),
    ('Books', 'Books'),
    ('Others', 'Others'),
]

class ListingForm(forms.ModelForm):
  category = forms.ChoiceField(choices=CATEGORY_CHOICES, required=False)

  class Meta:
    model = Listing
    fields = ["title", "description", "starting_bid", "image_url", "category"]

Project2_Auction/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Listing, Bid, Comment
from .forms import ListingForm
from decimal import Decimal


from .models import User
from django.contrib.auth.decorators import login_required



def index(request):
    active_listing = Listing.objects.filter(is_active=True)
    return render(request, "auctions/index.html", {
        "listings": active_listing
    })



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))



def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")



@login_required
def create_listing(request):

    if request.method == "POST":
        form = ListingForm(request.POST)

        if form.is_valid():
            listing = form.save(commit=False)
            listing.creator = request.user
            listing.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = ListingForm()
    
    return render(request, "auctions/create_listing.html", {
        "form": form
    })




def listing(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    comments = listing.comments.order_by("-timestamp")
    # user_is_watching = request.user in listing.watchlist.all()
    highest_bid = listing.bids.order_by('-amount').first()
    highest_bidder = highest_bid.bidder if highest_bid else None


    if request.method == "POST":

        if "place_bid" in request.POST:
            amount = float(request.POST["bid_amount"])
            min_bid = listing.starting_bid
            if highest_bid:
                min_bid = max(listing.starting_bid, highest_bid.amount + Decimal(0.01))
            
            if amount >= min_bid:
                Bid.objects.create(
                    listing = listing,
                    bidder = request.user,
                    amount = amount
                )
            else:
                return render(request, 'auctions/listing.html', {
                    "listing": listing,
                    "comments": comments,
                    "highest_bid": highest_bid,
                    "highest_bidder": highest_bidder,
                    "error": f"Your bid must be at least ${min_bid:.2f}"
                })
        
        elif "add_watchlist" in request.POST:
            listing.watchlist.add(request.user)
        
        elif "remove_watchlist" in request.POST:
            listing.watchlist.remove(request.user)

        
        elif "close_auction" in request.POST and request.user == listing.creator:
            listing.is_active = False
            if highest_bid:
                listing.winner = highest_bid.bidder
            listing.save()
        

        elif "add_comment" in request.POST:
            content = request.POST["comment"]
            Comment.objects.create(
                listing = listing,
                author = request.user,
                content = content
            )
        

        return redirect('listing', listing_id=listing.id)




    return render(request, 'auctions/listing.html', {
        "listing": listing,
        "comments": comments,
        "highest_bid": highest_bid,
        "highest_bidder": highest_bidder
    })





def watchlist(request):

    user_watchlist = request.user.watchlist.all()
    return render(request, "auctions/watchlist.html", {
        "watchlist": user_watchlist
    })




def categories(request):

    categories = Listing.objects.values_list("category", flat=True).distinct()
    return render(request, "auctions/categories.html", {
        "categories": categories
    })



def category_listing(request, category_name):
    listings = Listing.objects.filter(category= category_name, is_active=True)

    return render(request, "auctions/category_listing.html", {
        "category": category_name,
        "listings": listings
    })

Project2_Auction/commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}Categories{% endblock %}

{% block body %}

  <h2>Categories</h2>

  <ul>
    {% for category in categories %}
      {% if category %}
        <li><a href="{% url 'category_listing' category %}">{{ category }}</a></li>
      {% else %}
        <li>No categories found.</li>
      {% endif %}
    {% endfor %}
  </ul>

{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/category_listing.html
{% extends "auctions/layout.html" %}

{% block title %}{{ category }} Listing{% endblock %}

{% block body %}

  <h2>{{ category }} Items</h2>
  
  
  {% for listing in listings %}

      <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;" class="container-fluid">
          
          <div class="row">

              <div class="col-lg-4">
                  {% if listing.image_url %}
                      <img src="{{ listing.image_url }}" alt="image" style="max-height: 150px; max-width: 300px;display: block; margin-left: auto; margin-right: auto;">
                  {% endif %}
              </div>

              <div class="col-lg-8">
                  <h3><a href="{% url 'listing' listing.id %}">{{ listing.title }}</a></h3>

                  <p><strong>Price: ${{ listing.bids.amount|default:listing.starting_bid }} </strong></p>

                  <p>{{ listing.description|truncatechars:100 }}</p>
                  <p style="font-size: 14px; color: grey;">Created {{ listing.created_time }}</p>
              </div>
          </div>
      </div>
  {% endfor %}
{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}
{% load form_tags %}

{% block title %}Creating Listing{% endblock %}

{% block body %}


<h2>Create New Listing</h2>

<div class="container col-lg-8 mt-4">

  <form method="POST" class="mt-3">
    {% csrf_token %}

    <div class="form-group mt-3">
      <label for="id_title" class="form-label">Title:</label>
      {{ form.title|add_class:"form-control" }}
    </div>

    <div class="form-group mt-3">
      <label for="id_description" class="form-label">Description:</label>
      {{ form.description|add_class:"form-control" }}
    </div>

    <div class="form-group mt-3">
      <label for="id_starting_bid" class="form-label">Starting Bid ($):</label>
      {{ form.starting_bid|add_class:"form-control" }}
    </div>

    <div class="form-group mt-3">
      <label for="id_image_url" class="form-label">Image url:</label>
      {{ form.image_url|add_class:"form-control" }}
    </div>

    <div class="form-group mt-3">
      <label for="id_category" class="form-label">Category:</label>
      {{ form.category|add_class:"form-select" }}
    </div>
    
    <button type="submit" class="btn btn-primary mt-3">Create Listing</button>
  </form>

</div>
{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    {% for listing in listings %}

        <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;" class="container-fluid">
            
            <div class="row">

                <div class="col-lg-4">
                    {% if listing.image_url %}
                        <img src="{{ listing.image_url }}" alt="image" style="max-height: 150px; max-width: 300px;display: block; margin-left: auto; margin-right: auto;">
                    {% endif %}
                </div>

                <div class="col-lg-8">
                    <h3><a href="{% url 'listing' listing.id %}">{{ listing.title }}</a></h3>

                    <p><strong>Price: ${{ listing.bids.amount|default:listing.starting_bid }} </strong></p>

                    <p>{{ listing.description|truncatechars:100 }}</p>
                    <p style="font-size: 14px; color: grey;">Created {{ listing.created_time }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

Project2_Auction/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}{{ listing.title }}{% endblock %}

{% block body %}

<div class="container mt-4">

  <div class="d-flex justify-content-between align-items-center mb-3">

    <h2>Listing: {{ listing.title }}</h2>

    {% if user.is_authenticated %}

      {% if listing in user.watchlist.all %}
        <form action="{% url 'listing' listing.id %}" method="POST">
          {% csrf_token %}
          <input name="remove_watchlist" type="hidden" value="1">
          <button class="btn btn-danger btn-sm">Remove from Watchlist</button>
        </form>
      
        {% else %}
          <form action="{% url 'listing' listing.id %}" method="POST">
            {% csrf_token %}
            <input name="add_watchlist" type="hidden" value="1">
            <button class="btn btn-success btn-sm">Watchlist</button>
          </form>
        {% endif %}
    {% endif %}
  </div>


  {% if listing.image_url %}
    <img src="{{ listing.image_url }}" alt="{{ listing.title }}" style="max-height: 250; max-width: 500px;">
  {% endif %}

  <p>{{ listing.description }}</p>

  <h4>
    {% if highest_bid %}
      ${{ listing.starting_bid|floatformat:2 }}, <span style="color: grey; font-size: 20px;">(Current: ${{ highest_bid.amount|floatformat:2 }})</span>
    {% else %}
      ${{ listing.starting_bid|floatformat:2 }}
    {% endif %}
  </h4>
  <p>{{ listing.bids.count }} bid(s) so far.
    {% if user.is_authenticated and user == highest_bidder %}
      Your bid is the highest bid.
    {% endif %}
  </p>

  {% if listing.is_active %}
    {% if user.is_authenticated and user != listing.creator %}
      <form action="{% url 'listing' listing.id %}" method="POST" class="mb-4">
        {% csrf_token %}
        <input name="place_bid" type="hidden" value="1">
        <div class="input-group mb-2" style="max-width: 300px">
          <span class="input-group-text">$</span>
          <input type="number" step="0.01" name="bid_amount" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Place Bid</button>
      </form>

      {% if error %}
        <p style="color: red;">{{ error }}</p>
      {% endif %}
    {% endif %}

    {% if user.is_authenticated and user == listing.creator %}
      <form action="{% url 'listing' listing.id %}" method="POST" class="mb-4">
        {% csrf_token %}
        <input name="close_auction" type="hidden" value="1">
        <button type="submit" class="btn btn-danger">Close Auction</button>
      </form>
    {% endif %}

  {% else %}
    <div class="alert alert-info">
      This auction is closed.
      {% if user == highest_bidder %}
        You won this auction!
      {% endif %}
    </div>
  {% endif %}



  <h5>Details:</h5>
  <ul>
    <li>Listed by: <strong>{{ listing.creator }}</strong></li>
    <li>Category: {{ listing.category|default:"None" }}</li>
  </ul>



  <h5 class="mt-5">Comments:</h5>
  {% if user.is_authenticated %}
    <form action="{% url 'listing' listing.id %}" method="POST" class="mb-4">
      {% csrf_token %}
      <input name="add_comment" type="hidden" value="1">
      <div class="mb-2">
        <textarea name="comment" class="form-control" rows="3" placeholder="Add a comment here..." required></textarea>
      </div>
      <button class="btn btn-success">Add</button>
    </form>
  {% endif %}


  <ul class="list-group mb-3">
    {% for comment in comments %}
      <li class="list-group-item">
        <strong>{{ comment.author }}</strong> ({{ comment.timestamp|date:"Y-m-d H:i" }}):
        <br>
        {{ comment.content }}
      </li>
    {% empty %}
      <li class="list-group-item">No comments.</li>
    {% endfor %}
  </ul>


</div>

{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

Project2_Auction/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}Watchlist{% endblock %}

{% block body %}

  <h2>Your watchlist</h2>

  {% for listing in watchlist %}

        <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;" class="container-fluid">
            
            <div class="row">

                <div class="col-lg-4">
                    {% if listing.image_url %}
                        <img src="{{ listing.image_url }}" alt="image" style="max-height: 150px; max-width: 300px;display: block; margin-left: auto; margin-right: auto;">
                    {% endif %}
                </div>

                <div class="col-lg-8">
                    <h3><a href="{% url 'listing' listing.id %}">{{ listing.title }}</a></h3>

                    <p><strong>Price: ${{ listing.bids.amount|default:listing.starting_bid }} </strong></p>

                    <p>{{ listing.description|truncatechars:100 }}</p>
                    <p style="font-size: 14px; color: grey;">Created {{ listing.created_time }}</p>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}